server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/play_video?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 200309
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
      # 如果需要密码，取消注释下一行
      # password: 

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ligg.entity
  configuration:
    map-underscore-to-camel-case: true

# JWT配置
jwt:
  # token有效期（单位：秒）
  expiration: 86400  # 24小时
  # token头部
  header: Authorization
  # token前缀
  tokenPrefix: "Bearer "
